<?php

/**
 * Copyright © 2021 Bertozzi Matteo
 *
 * PHP Version 5
 *
 * @category File
 * @package  Lvk_Design
 * @author   Bertozzi Matteo <brtzz.mtt@gmail.com>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://github.com/brtzz-mtt
 */

?>

<table cellspacing="0">
    <tr>
        <td>
            iPhone SE Portrait 320x480<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone4"
                    width="320"
                    height="480">
            </iframe>
        </td>
        <td>
            iPhone 5 Portrait 320x568<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone5"
                    width="320"
                    height="568">
            </iframe>
        </td>
        <td>
            iPhone 6/7 Portrait 375x667<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone6"
                    width="375"
                    height="667">
            </iframe>
        </td>
        <td>
            iPhone 6/7 Plus Portrait 414x736<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone6 Plus"
                    width="414"
                    height="736">
            </iframe>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            iPhone SE Landscape 480x320<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone4"
                    width="480"
                    height="320">
            </iframe>
        </td>
        <td colspan="2">
            iPhone 5 Landscape 568x320<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone5"
                    width="568"
                    height="320">
            </iframe>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            iPhone 6/7 Landscape 667x375<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone6"
                    width="667"
                    height="375">
            </iframe>
        </td>
        <td colspan="2">
            iPhone 6/7 Plus Landscape 736x414<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPhone6 Plus"
                    width="736"
                    height="414">
            </iframe>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            iPad Portrait 768x1024<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPad Portrait"
                    width="768"
                    height="1024">
            </iframe>
        </td>
        <td colspan="2">
            iPad Landscape 1024x768<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="iPad Landscape"
                    width="1024"
                    height="768">
            </iframe>
        </td>
    </tr>
    <tr>
       <td colspan="4">
            Desktop wide 1180px<br />
            <br />
            <iframe src="<?php echo $block->getUrlToResponsivize() ?>"
                    name="Desktop wide 1180px"
                    width="1180"
                    height="2360">
            </iframe>
        </td>
    </tr>
</table>
