<?php

/**
 * Copyright © 2021 Bertozzi Matteo
 *
 * PHP Version 5
 *
 * @category File
 * @package  Lvk_Design
 * @author   Bertozzi Matteo <brtzz.mtt@gmail.com>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://github.com/brtzz-mtt
 */

?>

<fieldset>
    <legend><?php echo __("Colors") ?></legend>
    <div>
        <span class="theme-color background-color" style="width:99.666%">
            <?php echo __("Background color with default text") ?>
            <br />
            @background-color / @text-color
        </span>
    </div>
    <div>
        <span class="theme-color primary-color-brighter">
            <?php echo __("Primary") . '-' . __("color") . ' ' . __("brighter") ?>
            <br />
            @primary-color-brighter
        </span>
        <span class="theme-color primary-color-bright">
            <?php echo __("Primary") . '-' . __("color") . ' ' . __("bright") ?>
            <br />
            @primary-color-bright
        </span>
        <span class="theme-color primary-color">
            <?php echo __("Primary") . '-' . __("color") ?>
            <br />
            @primary-color
        </span>
        <span class="theme-color primary-color-dark">
            <?php echo __("Primary") . '-' . __("color") . ' ' . __("dark") ?>
            <br />
            @primary-color-dark
        </span>
        <span class="theme-color primary-color-darker">
            <?php echo __("Primary") . '-' . __("color") . ' ' . __("darker") ?>
            <br />
            @primary-color-darker
        </span>
    </div>
    <div>
        <span class="theme-color secondary-color-brighter">
            <?php echo __("Secondary") . '-' . __("color") . ' ' . __("brighter") ?>
            <br />
            @secondary-color-brighter
        </span>
        <span class="theme-color secondary-color-bright">
            <?php echo __("Secondary") . '-' . __("color") . ' ' . __("bright") ?>
            <br />
            @secondary-color-bright
        </span>
        <span class="theme-color secondary-color">
            <?php echo __("Secondary") . '-' . __("color") ?>
            <br />
            @secondary-color
        </span>
        <span class="theme-color secondary-color-dark">
            <?php echo __("Secondary") . '-' . __("color") . ' ' . __("dark") ?>
            <br />
            @secondary-color-dark
        </span>
        <span class="theme-color secondary-color-darker">
            <?php echo __("Secondary") . '-' . __("color") . ' ' . __("darker") ?>
            <br />
            @secondary-color-darker
        </span>
    </div>
    <div>
        <span class="theme-color tertiary-color-brighter">
            <?php echo __("Tertiary") . '-' . __("color") . ' ' . __("brighter") ?>
            <br />
            @tertiary-color-brighter
        </span>
        <span class="theme-color tertiary-color-bright">
            <?php echo __("Tertiary") . '-' . __("color") . ' ' . __("bright") ?>
            <br />
            @tertiary-color-bright
        </span>
        <span class="theme-color tertiary-color">
            <?php echo __("Tertiary") . '-' . __("color") ?>
            <br />
            @tertiary-color
        </span>
        <span class="theme-color tertiary-color-dark">
            <?php echo __("Tertiary") . '-' . __("color") . ' ' . __("dark") ?>
            <br />
            @tertiary-color-dark
        </span>
        <span class="theme-color tertiary-color-darker">
            <?php echo __("Tertiary") . '-' . __("color") . ' ' . __("darker") ?>
            <br />
            @tertiary-color-darker
        </span>
    </div>
    <div>
        <span class="theme-color grey-brighter">
            <?php echo __("Grey") . ' ' . __("brighter") ?>
            <br />
            @grey-brighter
        </span>
        <span class="theme-color grey-bright">
            <?php echo __("Grey") . ' ' . __("bright") ?>
            <br />
            @grey-bright
        </span>
        <span class="theme-color grey-normal">
            <?php echo __("Grey") . ' ' . __("normal") ?>
            <br />
            @grey-normal
        </span>
        <span class="theme-color grey-dark">
            <?php echo __("Grey") . ' ' . __("dark") ?>
            <br />
            @grey-dark
        </span>
        <span class="theme-color grey-darker">
            <?php echo __("Grey") . ' ' . __("darker") ?>
            <br />
            @grey-darker
        </span>
    </div>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __("Headlines") ?></legend>
    <h1 class="display">Headline tag H1.display</h1>
    <h1>Headline tag H1</h1>
    <h2>Headline tag H2</h2>
    <h3>Headline tag H3</h3>
    <h4>Headline tag H4</h4>
    <h5>Headline tag H5</h5>
    <h5 class="muted">Headline tag H5.muted</h5>
    <h6>Headline tag H6</h6>
    <h6 class="muted">Headline tag H6.muted</h6>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __("Text elements") ?></legend>
    <p class="lead">
        Paragraph tag P.lead:
    </p>
    <p>
        Paragraph tag P: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Sed id fringilla lacus.
        Maecenas nisi mi, suscipit in consequat id, tempus sed orci.
    </p>
    <p>
        <big>Paragraph tag P + BIG: Maecenas quis ante gravida ex ultrices.</big>
    </p>
    <p>
        <small>Paragraph tag P + SMALL: Curabitur ultricies dignissim cursus.</small>
    </p>
    <p>
        <blockquote>
            Paragraph tag P + BLOCKQUOTE: Mauris lacinia pellentesque ex, id blandit.
        </blockquote>
        <em>Paragraph tag P + EM</em>
    </p>
    <p>
        Aenean blandit sapien sit amet dui tincidunt mattis.
        <strong>
            Paragraph tag P + STRONG: Integer congue dictum porta.
            Quisque convallis suscipit diam non faucibus.
        </strong>
    </p>
    <strong>Text tag STRONG</strong>
    <br />
    <b>Text tag B</b>
    <br />
    <blockquote>
        Text tag BLOCKQUOTE
        <br />
        <small><em>Text tag SMALL + EM</em></small>
    </blockquote>
    <big>Text tag BIG</big>
    <br />
    <small>Text tag SMALL</small>
    <br />
    <em>Text tag EM</em>
    <br />
    <i>Text tag I</i>
    <br />
    <a>Anchor tag A</a>
    <br />
    <ul>
        <li>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
        </li>
        <li>
            <p>
                Sed id fringilla lacus.
            </p>
            <ul>
                <li>
                    <p>
                        Maecenas nisi mi, suscipit in consequat id, tempus sed orci.
                    </p>
                </li>
                <li>
                    <p>
                        Maecenas quis ante gravida ex lacinia ultrices.
                    </p>
                </li>
            </ul>
        </li>
        <li>
            <p>
                Curabitur ultricies dignissim cursus.
            </p>
            <ul>
                <li>
                    <p>
                        Mauris lacinia pellentesque ex, id blandit tortor ornare sed.
                    </p>
                </li>
                <ul>
                    <li>
                        <p>
                            Aenean blandit sapien sit amet dui tincidunt mattis.
                        </p>
                    </li>
                    <li>
                        <p>
                            Integer congue dictum porta.
                        </p>
                    </li>
                    <li>
                        <p>
                            Quisque convallis suscipit diam non faucibus.
                        </p>
                    </li>
                </ul>
            </ul>
         </li>
    </ul>
    <ol>
        <li>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
        </li>
        <li>
            <p>
                Sed id fringilla lacus.
            </p>
            <ol>
                <li>
                    <p>
                        Maecenas nisi mi, suscipit in consequat id, tempus sed orci.
                    </p>
                </li>
                <li>
                    <p>
                        Maecenas quis ante gravida ex lacinia ultrices.
                    </p>
                </li>
            </ol>
        </li>
        <li>
            <p>
                Curabitur ultricies dignissim cursus.
            </p>
            <ol>
                <li>
                    <p>
                        Mauris lacinia pellentesque ex, id blandit tortor ornare sed.
                    </p>
                </li>
                <ol>
                    <li>
                        <p>
                            Aenean blandit sapien sit amet dui tincidunt mattis.
                        </p>
                    </li>
                    <li>
                        <p>
                            Integer congue dictum porta.
                        </p>
                    </li>
                    <li>
                        <p>
                            Quisque convallis suscipit diam non faucibus.
                        </p>
                    </li>
                </ol>
            </ol>
         </li>
    </ol>
</fieldset>
<br />
<fieldset>
    <legend><?php echo __("Widgets") ?></legend>
    <button class="small">
        <span><?php echo __("Small normal button") ?></span>
    </button>
    <button>
        <span><?php echo __("Normal button") ?></span>
    </button>
    <button class="big">
        <span><?php echo __("Big normal button") ?></span>
    </button>
    <br />
    <button class="bright small">
        <span><?php echo __("Small bright button") ?></span>
    </button>
    <button class="bright">
        <span><?php echo __("Normal bright button") ?></span>
    </button>
    <button class="bright big">
        <span><?php echo __("Big bright button") ?></span>
    </button>
    <br />
    <button class="dark small">
        <span><?php echo __("Small dark button") ?></span>
    </button>
    <button class="dark">
        <span><?php echo __("Normal dark button") ?></span>
    </button>
    <button class="dark big">
        <span><?php echo __("Big dark button") ?></span>
    </button>
    <br />
    <form>
        <br />
        <input type="text" placeholder="Text input" />
        <br />
        <br />
        <input type="number" value="1" min="1" max="99" />
        <br />
        <br />
        <input type="submit" value="Small normal submit" class="small" />
        <input type="submit" value="Normal submit" />
        <input type="submit" value="Big normal submit" class="big" />
        <br />
        <input type="submit" value="Small bright submit" class="bright small" />
        <input type="submit" value="Normal bright submit" class="bright" />
        <input type="submit" value="Big bright submit" class="bright big" />
        <br />
        <input type="submit" value="Small dark submit" class="dark small" />
        <input type="submit" value="Normal dark submit" class="dark" />
        <input type="submit" value="Big dark submit" class="dark big" />
        <br />
        <br />
        <select>
            <option value="0" selected disabled>Select box</option>
            <option value="1">Option 1</option>
            <option value="2">Option 2</option>
            <option value="3">Option 3</option>
        </select>
    </form>
</fieldset>

<script type="text/javascript">
    require([
        'jquery'
    ], function($)
    {
        $('fieldset .theme-color').each(function()
        {
            var html = $(this).html(),
                backgroundColor = $(this).css('background-color');

            if (backgroundColor == 'rgba(0, 0, 0, 0)') {

                $(this).hide();
                $(this).siblings('.theme-color').hide();

            } else {

                $(this).html(html + '<br />' + backgroundColor);
            }

            if ($(this).hasClass('background-color')) {

                $(this).html($(this).html() + ' / ' + $(this).css('color'));
            }
        });
    });
</script>
