<?php

/**
 * Copyright © 2021 Bertozzi Matteo
 *
 * PHP Version 5
 *
 * @category File
 * @package  Lvk_Base
 * @author   Bertozzi Matteo <brtzz.mtt@gmail.com>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://github.com/brtzz-mtt
 */

if ($block->getCollection()->getSize()) {
    ?>
    <div class="toolbar toolbar-products"
         data-mage-init='<?php echo $block->getWidgetOptionsJson() ?>'>
        <?php
        if ($block->showCategoryTitle()) {
            ?>
            <h1>
                <?php
                $pageTitleBlock = $block->getLayout()->getBlock('page.main.title');
                echo $pageTitleBlock->getPageTitle();
                ?>
            </h1>
            <?php
        }
        ?>

        <?php
        if ($block->isExpanded()) {

            $template = 'Magento_Catalog::product/list/toolbar/viewmode.phtml';

            echo $block->setTemplate($template)->toHtml();
        }

        $template = 'Magento_Catalog::product/list/toolbar/amount.phtml';
        echo $block->setTemplate($template)->toHtml();

        echo $block->getPagerHtml();

        if ($block->showFieldLimiter()) {

            $template = 'Magento_Catalog::product/list/toolbar/limiter.phtml';

            echo $block->setTemplate($template)->toHtml();
        }

        if ($block->isExpanded()) {

            echo $block->setTemplate($block->getSorterTemplate())->toHtml();
        }
        ?>
    </div>
    <?php
}
