<?php

/**
 * Copyright © 2021 Bertozzi Matteo
 *
 * PHP Version 5
 *
 * @category File
 * @package  Lvk_Design
 * @author   Bertozzi Matteo <brtzz.mtt@gmail.com>
 * @license  The PHP License, Version 3.0 - PHP.net (http://php.net/license/3_0.txt)
 * @link     https://github.com/brtzz-mtt
 */

?>

<div class="sidebar title"
     rel="<?php echo $block->getSidebarType() ?>">
    <div class="sidebar-title">
        <strong><?php echo $block->getTitle() ?></strong>
    </div>
</div>
